[package]
name = "kv"
version = "0.1.0"
authors = ["Christopher Henn <chris@chrishenn.net>"]
edition = "2018"

[dependencies]
structopt = "0.2"
tempfile = "3.0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
